packages:
  - apps/nuxt
  - apps/vscode-web
  - apps/vscode
  - packages/*
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  less: set this to true or false
  sharp: set this to true or false
